<a href="https://colab.research.google.com/github/muhammedafsalpm/Emergio_Games_Training/blob/main/Emergio_Games_Day_5(21_08_24).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Questions (Day - 5 21/08/2024)

1. Write a Python program to create a 1D NumPy array with values from 0 to 9.

In [9]:
import numpy as np
array = np.arange(10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


2. Write a Python program to create a 2D NumPy array with values from 1 to 9 arranged in 3 rows and 3 columns.

In [10]:
import numpy as np

array = np.reshape(np.arange(1, 10), (3, 3))
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Write a Python program to find the shape of a NumPy array.

In [11]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
shape = array.shape

print(shape)

(2, 3)


4. Write a Python program to find the data type of elements in a NumPy array.

In [13]:
import numpy as np
array = np.array([1, 2.5, "Hello", True])

data_types = array.dtype
print(data_types)

<U32


5. Write a Python program to create a NumPy array filled with zeros.

In [14]:
import numpy as np

array = np.zeros((4,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6. Write a Python program to create a NumPy array filled with ones.

In [15]:
import numpy as np

array = np.ones((4,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


7. Write a Python program to create an identity matrix of size 3x3 using NumPy.

In [27]:
import numpy as np

#Method 1
identity_matrix = np.eye(3, 3)
print(identity_matrix)

#Method 2
identity_matrix_2 = np.identity(3)
print(identity_matrix_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Write a Python program to generate a NumPy array of random numbers.

In [28]:
import numpy as np
random_array = np.random.rand(5)

print(random_array)

[0.08049139 0.95584113 0.51822659 0.47080533 0.53459158]


9. Write a Python program to find the maximum value in a NumPy array.

In [33]:
size = int(input("Enter the size of the array: "))
array = np.zeros(size)

for i in range(size):
    array[i] = float(input(f"Enter element {i+1}: "))

max_value = np.max(array)
print(max_value)

Enter the size of the array: 5
Enter element 1: 12
Enter element 2: 89
Enter element 3: 66
Enter element 4: 25
Enter element 5: 10
89.0


10. Write a Python program to find the minimum value in a NumPy array.

In [34]:
size = int(input("Enter the size of the array: "))
array = np.zeros(size)

for i in range(size):
  array[i] = float(input(f"Enter element {i+1}: "))

min_value = np.min(array)
print("Minimum Value is :",min_value)

Enter the size of the array: 5
Enter element 1: 25
Enter element 2: 40
Enter element 3: 03
Enter element 4: 96
Enter element 5: 5
Minimum Value is : 3.0


11. Write a Python program to calculate the sum of all elements in a NumPy array.

In [35]:
size = int(input("Enter the size of the array: "))
array = np.zeros(size)
for i in range(size):
  array[i] = float(input(f"Enter element {i+1}: "))

print("Sum is ",sum(array))

Enter the size of the array: 4
Enter element 1: 32
Enter element 2: 74
Enter element 3: 10
Enter element 4: 13
Sum is  129.0


12. Write a Python program to calculate the mean of all elements in a NumPy array.

In [37]:
size = int(input("Enter the size of the array: "))
array = np.zeros(size)
for i in range(size):
  array[i] = float(input(f"Enter element {i+1}: "))

print("Sum is ",np.mean(array))

Enter the size of the array: 5
Enter element 1: 32
Enter element 2: 85
Enter element 3: 10
Enter element 4: 60
Enter element 5: 5
Sum is  38.4


13. Write a Python program to create a 2D NumPy array and flatten it to a 1D array.

In [38]:
import numpy as np

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

array_2d = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        array_2d[i, j] = float(input(f"Enter element ({i+1}, {j+1}): "))
array_1d = array_2d.flatten()

print("Flattened array:", array_1d)

Enter the number of rows: 3
Enter the number of columns: 2
Enter element (1, 1): 10
Enter element (1, 2): 56
Enter element (2, 1): 15
Enter element (2, 2): 96
Enter element (3, 1): 02
Enter element (3, 2): 30
Flattened array: [10. 56. 15. 96.  2. 30.]


14. Write a Python program to create a NumPy array and reshape it to a different shape.

In [40]:
import numpy as np

array = np.array([74, 62, 43, 85, 52, 6])
array_reshaped = array.reshape(2,3)

print(array_reshaped)

[[74 62 43]
 [85 52  6]]


15. Write a Python program to stack two NumPy arrays vertically.

In [42]:
import numpy as np

array1 = np.array([11, 52, 41])
array2 = np.array([43, 55, 17])

stacked_array = np.vstack((array1, array2))
print(stacked_array)

[[11 52 41]
 [43 55 17]]


16. Write a Python program to stack two NumPy arrays horizontally.

In [43]:
import numpy as np

array1 = np.array([11, 52, 41])
array2 = np.array([43, 55, 17])

stacked_array = np.hstack((array1, array2))
print(stacked_array)

[11 52 41 43 55 17]


17. Write a Python program to create a NumPy array and reverse its elements.

In [44]:
import numpy as np

array = np.array([74, 62, 43, 85, 52, 6])
reversed_array = array[::-1]


print(reversed_array)

[ 6 52 85 43 62 74]


18. Write a Python program to find the unique elements in a NumPy array.

In [46]:
import numpy as np

array = np.array([14, 14, 10, 3, 3, 44])

unique_elements = np.unique(array)
print(unique_elements)

[ 3 10 14 44]


19. Write a Python program to create a NumPy array and find its transpose.

In [52]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.T)

[[1 4]
 [2 5]
 [3 6]]


20. Write a Python program to slice a NumPy array and print a specific section of it.

In [53]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliced_array = array[:2, 1]
print(sliced_array)

[2 5]


21. Write a Python program to perform element-wise addition of two NumPy arrays

In [54]:
import numpy as np

array1 = np.array([11, 42, 63])
array2 = np.array([54, 45, 6])

result = array1 + array2

print(result)

[65 87 69]


22. Write a Python program to perform element-wise multiplication of two NumPy arrays.

In [55]:
import numpy as np

array1 = np.array([11, 42, 63])
array2 = np.array([54, 45, 6])

result = array1 * array2

print(result)

[ 594 1890  378]


23. Write a Python program to calculate the dot product of two NumPy arrays.

In [56]:
import numpy as np

array1 = np.array([11, 42, 63])
array2 = np.array([54, 45, 6])

result = np.dot(array1,array2)

print(result)

2862


24. Write a Python program to multiply a NumPy array by a scalar value.

In [57]:
import numpy as np

array = np.array([74, 62, 43, 85, 52, 6])

scalar_value = 2
result = array * scalar_value

print(result)

[148 124  86 170 104  12]


25. Write a Python program to find the inverse of a 2x2 NumPy matrix.

In [58]:
import numpy as np
matrix = np.array([[24, 11],
                   [83, 48]])

inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[ 0.20083682 -0.0460251 ]
 [-0.34728033  0.10041841]]


26. Write a Python program to solve a system of linear equations using NumPy.

In [59]:
import numpy as np

coefficients = np.array([[2, 1],
                         [3, 4]])
constants = np.array([5, 11])

solution = np.linalg.solve(coefficients, constants)

print(solution)

[1.8 1.4]


27. Write a Python program to compute the eigenvalues and eigenvectors of a square NumPy matrix.

In [61]:
import numpy as np

matrix = np.array([[11, 55],
                   [31, 43]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-17.28317965  71.28317965]
Eigenvectors: [[-0.88930447 -0.67399421]
 [ 0.4573156  -0.73873662]]


28. Write a Python program to calculate the determinant of a square NumPy matrix.

In [62]:
import numpy as np

matrix = np.array([[11, 55],
                   [31, 43]])

determinant = np.linalg.det(matrix)
print("Determinant is ",determinant)

Determinant is  -1232.0000000000007


29. Write a Python program to find the sum of elements along the diagonal of a NumPy matrix.

In [63]:
import numpy as np

matrix = np.array([[14, 74, 43],
                   [4, 54, 55],
                   [47, 84, 9]])

diagonal_sum = np.trace(matrix)

print("Diagonal sum:", diagonal_sum)

Diagonal sum: 77


30. Write a Python program to find the cumulative sum of elements in a NumPy array.

In [64]:
import numpy as np

array = np.array([74, 62, 43, 85, 52, 6])
cumulative_sum = np.cumsum(array)

print(cumulative_sum)

[ 74 136 179 264 316 322]


31. Write a Python program to perform matrix multiplication using NumPy.

In [65]:
import numpy as np

matrix1 = np.array([[11, 42],
                    [41, 47]])
matrix2 = np.array([[75, 46],
                    [78, 80]])

result = np.dot(matrix1, matrix2)

print(result)

[[4101 3866]
 [6741 5646]]


32. Write a Python program to compute the cross product of two 3D NumPy vectors.

In [66]:
import numpy as np

vector1 = np.array([54, 72, 43])
vector2 = np.array([14, 45, 56])

cross_product = np.cross(vector1, vector2)
print(cross_product)

[ 2097 -2422  1422]


33. Write a Python program to implement the convolution of two 1D NumPy arrays.

In [68]:
import numpy as np

matrix1 = np.array([54, 72, 43])
matrix2 = np.array([14, 45, 56])

y = np.convolve(matrix1, matrix2, mode='full')

print(y)

[ 756 3438 6866 5967 2408]


34. Write a Python program to compute the Fast Fourier Transform (FFT) of a NumPy array.

In [72]:
import numpy as np

array = np.array([5, 5, 3, 4, 7])

fft_result = np.fft.fft(array)
print(fft_result)

[24.        +0.j          3.04508497+2.48989828j -2.54508497+0.22451399j
 -2.54508497-0.22451399j  3.04508497-2.48989828j]


35. Write a Python program to perform singular value decomposition (SVD) on a NumPy matrix.

In [73]:
import numpy as np

matrix = np.array([[14, 45],
                   [43, 77]])

U, sigma, VT = np.linalg.svd(matrix)

print("U:",U)
print("Sigma:",sigma)
print("V^H:",VT)


U: [[-0.46684839 -0.88433737]
 [-0.88433737  0.46684839]]
Sigma: [99.62429474  8.60231937]
V^H: [[-0.44730439 -0.89438179]
 [ 0.89438179 -0.44730439]]


36. Write a Python program to generate a random 3D NumPy array and find the indices of the maximum value.

In [74]:
import numpy as np

random_array = np.random.rand(13, 42, 35)

max_indices = np.unravel_index(np.argmax(random_array), random_array.shape)
print("Indices of the maximum value:", max_indices)

Indices of the maximum value: (9, 12, 0)


37. Write a Python program to solve a quadratic equation using NumPy.

In [75]:
import numpy as np

a = 1
b = -5
c = 6

discriminant = b**2 - 4*a*c

if discriminant > 0:
    x1 = (-b + np.sqrt(discriminant)) / (2*a)
    x2 = (-b - np.sqrt(discriminant)) / (2*a)
    print("Solutions:", x1, x2)
elif discriminant == 0:
    x = -b / (2*a)
    print("Solution:", x)
else:
    print("No real solutions.")

Solutions: 3.0 2.0


38. Write a Python program to perform matrix exponentiation using NumPy.

In [76]:
import numpy as np

matrix = np.array([[14, 82],
                   [43, 48]])

matrix_exp = np.linalg.matrix_power(matrix, 3)
print(matrix_exp)

[[270720 549236]
 [288014 498452]]


39. Write a Python program to create a 3x3x3 NumPy array with random values and compute its inverse.

In [77]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
inverse_array = np.linalg.inv(random_array)

print("Inverse matrix:")
print(inverse_array)

Inverse matrix:
[[[-3.56296733 -1.61363734  3.61885728]
  [14.80924674  1.79482519 -8.01111671]
  [-1.88783029  1.49788368  0.62631502]]

 [[-0.15888195 -0.14341685  1.75553909]
  [-0.64448226  2.06729108  0.26041865]
  [ 1.89583367 -2.16562854 -1.27779864]]

 [[-4.42916445  3.6803297   3.26074878]
  [ 2.15433874 -0.70628746 -1.80320919]
  [ 4.118948   -3.52696803 -1.74901606]]]


40. Write a Python program to implement a simple linear regression using NumPy.

In [78]:
import numpy as np

X = np.array([[7, 1],
              [3, 9],
              [3, 6]])
y = np.array([2, 4, 6])

X = np.hstack((np.ones((X.shape[0], 1)), X))

coefficients = np.linalg.inv(X.T @ X) @ X.T @ y

slope = coefficients[1]
intercept = coefficients[0]

print("Slope:", slope)
print("Intercept:", intercept)

Slope: -1.8333333333333446
Intercept: 15.500000000000098
